# Generated by Django 3.2.9 on 2021-12-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillarquestapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='pillars',
            field=models.ManyToManyField(related_name='CompletedQuests', through='pillarquestapi.QuestPillar', to='pillarquestapi.Pillars'),
        ),
    ]
