# Generated by Django 3.2.10 on 2021-12-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillarquestapi', '0002_quest_pillars'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
